### PR TITLE
Add postcss-initial

### PR DESCRIPTION
**Pull request by maximkoretskiy**

### CODE REVIEW

**Comment by maximkoretskiy** [comment]
In your editorconfig is set 
```
end_of_line = lf
```
but `src/features.js` used `crlf`
My editor automaticaly fixed that.

**Comment by MoOx** [comment]
Can you provide link to specification please?
Is there any drawbacks for this plugin?

**Comment by maximkoretskiy** [comment]
`all` specification: https://drafts.csswg.org/css-cascade/#all-shorthand
`all` browsers support: http://caniuse.com/#feat=css-all
`initial` value specification: https://drafts.csswg.org/css-cascade/#initial-value
`initial` value browser support: http://caniuse.com/#feat=css-initial-value

Plugin can be useful for creating isolated components.

It supports `initial` value for  all properties. Also it supports `all: initial`.
It does not support `all: unset` and `all: inherit`.

**Comment by maximkoretskiy** [comment]
@MoOx, is everything fine?

**Comment by MoOx** [comment]
Can you add the can i use key in the activation map please ?

**Comment by maximkoretskiy** [comment]
@MoOx  done

**Comment by MoOx** [comment]
👌🏼

**Comment by MoOx** [comment]
Released as postcss-cssnext 2.1.0

**Pull request merged**
