### PR TITLE
Add plugins

### PR DESCRIPTION
**Pull request by jedmao**
See #2

### CODE REVIEW

**Comment by jedmao** [comment]
For some reason, tape is failing silently on my machine, which makes it very difficult to debug!

**Comment by MoOx** [comment]
did you try tape-catch ?

**Comment by jedmao** [comment]
@MoOx [tape-catch](https://github.com/michaelrhodes/tape-catch) doesn't appear to fail either. You can see from the Travis vs. AppVeyor builds that it fails on Travis and succeeds on AppVeyor. Looks like a Windows issue? (I'm on Windows BTW).

Anyway, I need to go to sleep. Will resume tomorrow.

**Comment by jedmao** [comment]
It might even be a Node issue, because switching the npm task to `sh node_modules/.bin/tape './lib/__tests__/*.js'` works as I would expect.

**Comment by MoOx** [comment]
what is your npm version ?

**Comment by drKraken** [comment]
@jedmao What node version do you use? it might be some issue with latest node(4.0.0) update.

**Comment by jedmao** [comment]
@drKraken I was using 4.0; however, I replaced it with 0.12.7 after your comment and it seems to be working properly now.

**Comment by jedmao** [comment]
Actually, I'm still experiencing the same issue on Node 0.12.7 and, apparently, so is AppVeyor. As you can see in [the AppVeyor output](https://ci.appveyor.com/project/MoOx/postcss-cssnext/build/7/job/hayeum5xlt842j99), tape doesn't even report which tests were run, if any, and it remains silent. Still, tape-catch didn't catch anything because there were no errors to catch. I think it didn't even run the tests on Windows! (Note: I removed tape-catch from this PR).

**Comment by jedmao** [comment]
@MoOx the features tests are all now passing. Are there any other tests you want me to capture here?

**Comment by MoOx** [comment]
Great job. I would add tests for the `browsers` option and I think it would be good for a start :)

**Comment by jedmao** [comment]
@MoOx I've added one more commit to test the browsers option. Did I miss anything else?

**Comment by MoOx** [comment]
Don't think so. Thanks !

**Comment by MoOx** [comment]
Any idea why we still have a warning https://travis-ci.org/cssnext/postcss-cssnext/jobs/79601850#L294 ?

**Comment by jedmao** [comment]
Yes, @MoOx. See https://github.com/iamvdo/pleeease-filters/pull/12

**Pull request merged**
